Day 5
=====

First file is seeds. Each addtional file is a map:

seed->soil

soil->fert

fert->water

water->light

light->temp

temp->humid

humid->location

All maps are arranged dest start, source start, range

e.g.,

    50 98 2
    52 50 48

The first line has a destination range start of 50, a source range start of 98, and a range length of 2. This line means that the source range starts at 98 and contains two values: 98 and 99. The destination range is the same length, but it starts at 50, so its two values are 50 and 51. With this information, you know that seed number 98 corresponds to soil number 50 and that seed number 99 corresponds to soil number 51.

The second line means that the source range starts at 50 and contains 48 values: 50, 51, ..., 96, 97. This corresponds to a destination range starting at 52 and also containing 48 values: 52, 53, ..., 98, 99. So, seed number 53 corresponds to soil number 55.

find the lowest location number that corresponds to any of the initial seeds

In [1]:
import numpy as np
import pandas as pd
n = np.loadtxt("5_seeds.txt", dtype = int,comments=None)
df=pd.DataFrame ({"Seeds": n})

#This function will do the mapping
def mapperFun(x,sendArray):
    for i in range(len(sendArray)):
        if (x>=sendArray[i][1] and x<(sendArray[i][1]+sendArray[i][2])):
            return (x-sendArray[i][1]+sendArray[i][0])
    return x

In [2]:
seeds2soil = np.loadtxt("5_seed2soil.txt", dtype = int,comments=None)
df["Soil"]=df.apply(lambda x: mapperFun(x.Seeds,seeds2soil),axis=1)

soil2fert = np.loadtxt("5_soil2fert.txt", dtype = int,comments=None)
df["Fert"]=df.apply(lambda x: mapperFun(x.Soil,soil2fert),axis=1)

fert2water = np.loadtxt("5_fert2water.txt", dtype = int,comments=None)
df["Water"]=df.apply(lambda x: mapperFun(x.Fert,fert2water),axis=1)

water2light = np.loadtxt("5_water2light.txt", dtype = int,comments=None)
df["Light"]=df.apply(lambda x: mapperFun(x.Water,water2light),axis=1)

light2temp = np.loadtxt("5_light2temp.text", dtype = int,comments=None)
df["Temp"]=df.apply(lambda x: mapperFun(x.Light,light2temp),axis=1)

temp2hum = np.loadtxt("5_temp2hum.txt", dtype = int,comments=None)
df["Hum"]=df.apply(lambda x: mapperFun(x.Temp,temp2hum),axis=1)

hum2loc = np.loadtxt("5_hum2loc.txt", dtype = int,comments=None)
df["Loc"]=df.apply(lambda x: mapperFun(x.Hum,hum2loc),axis=1)

In [3]:
min(df["Loc"])

196167384

Part 2
======

In [4]:
#m=[79, 14, 55, 13]   #for testing
seeds=[] 

for i in range(0,len(n),2):
    seeds=np.append(seeds, np.linspace(n[i],n[i]+n[i+1]-1,n[i+1]) )
#headsup this takes forever! I'm obviously missing something... 

NameError: name 'seeds' is not defined

In [1]:
df=pd.DataFrame ({"Seeds": seeds})
seeds2soil = np.loadtxt("5_seed2soil.txt", dtype = int,comments=None)
df["Soil"]=df.apply(lambda x: mapperFun(x.Seeds,seeds2soil),axis=1)

soil2fert = np.loadtxt("5_soil2fert.txt", dtype = int,comments=None)
df["Fert"]=df.apply(lambda x: mapperFun(x.Soil,soil2fert),axis=1)

fert2water = np.loadtxt("5_fert2water.txt", dtype = int,comments=None)
df["Water"]=df.apply(lambda x: mapperFun(x.Fert,fert2water),axis=1)

water2light = np.loadtxt("5_water2light.txt", dtype = int,comments=None)
df["Light"]=df.apply(lambda x: mapperFun(x.Water,water2light),axis=1)

light2temp = np.loadtxt("5_light2temp.text", dtype = int,comments=None)
df["Temp"]=df.apply(lambda x: mapperFun(x.Light,light2temp),axis=1)

temp2hum = np.loadtxt("5_temp2hum.txt", dtype = int,comments=None)
df["Hum"]=df.apply(lambda x: mapperFun(x.Temp,temp2hum),axis=1)

hum2loc = np.loadtxt("5_hum2loc.txt", dtype = int,comments=None)
df["Loc"]=df.apply(lambda x: mapperFun(x.Hum,hum2loc),axis=1)

NameError: name 'pd' is not defined

In [ ]:
min(df["Loc"])

Ok... That is taking way too long. 1,951,135,283 (2 BILLION!) rows :.) 
maybe i can work backwards... I want the lowest location so i'll start by sorting that mapping


In [9]:
sorted(hum2loc,key=lambda x: x[0])

[array([         0, 1639932830,  187421121]),
 array([187421121, 276160075, 171076082]),
 array([ 358497203, 1012762605,  163293355]),
 array([521790558, 232394351,  43765724]),
 array([565556282, 224750566,   7643785]),
 array([573200067,         0,  23652296]),
 array([ 596852363, 1585957916,   53974914]),
 array([ 650827277, 1396448131,  189509785]),
 array([ 840337062, 1827353951,   64247170]),
 array([ 904584232, 1176055960,  117301258]),
 array([1021885490, 1293357218,  103090913]),
 array([1124976403, 1891601121,  169224107]),
 array([1294200510,   23652296,  201098270]),
 array([1495298780,  447236157,  565526448]),
 array([2177370950, 4100409404,  127152021]),
 array([2304522971, 2377882496,  116771158]),
 array([2421294129, 2789610530,   69756625]),
 array([2491050754, 3106979484,  131101580]),
 array([2622152334, 4006190278,   94219126]),
 array([2716371460, 3238081064,  142806662]),
 array([2859178122, 2177370950,    6068675]),
 array([2865246797, 3380887726,  170016558]),


In [10]:
sorted()

array([[ 358497203, 1012762605,  163293355],
       [3035263355, 2859367155,  247612329],
       [1021885490, 1293357218,  103090913],
       [4143961841, 3795114494,  151005455],
       [3578373583, 4227561425,    8426352],
       [2859178122, 2177370950,    6068675],
       [         0, 1639932830,  187421121],
       [ 521790558,  232394351,   43765724],
       [3838880131, 4235987777,   10124834],
       [1294200510,   23652296,  201098270],
       [2865246797, 3380887726,  170016558],
       [2177370950, 4100409404,  127152021],
       [3282875684, 3954902589,   51287689],
       [1124976403, 1891601121,  169224107],
       [3334163373, 3550904284,  244210210],
       [ 565556282,  224750566,    7643785],
       [3586799935, 2183439625,  194442871],
       [ 573200067,          0,   23652296],
       [3781242806, 3946119949,    8782640],
       [2716371460, 3238081064,  142806662],
       [2304522971, 2377882496,  116771158],
       [3790025446, 4246112611,   48854685],
       [14